;; -*- mode: eask; lexical-binding: t -*-

(package "helm-fuzzy"
         "0.1.6"
         "Fuzzy matching for helm source")

(website-url "https://github.com/jcs-elpa/helm-fuzzy")
(keywords "matching" "fuzzy" "helm" "source")

(package-file "helm-fuzzy.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "24.4")
(depends-on "helm")
(depends-on "flx")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
